name: development

on:
  push:
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        deno:
          [1.x, canary]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: examples/batching-requests.ts
        run: deno run --allow-net examples/batching-requests.ts

      - name: examples/receiving-a-raw-response.ts
        run: deno run --allow-net examples/receiving-a-raw-response.ts

      - name: examples/using-variables.ts
        run: deno run --allow-net examples/using-variables.ts